# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
formats:
    - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-23.11"
  jobs:
    post_create_environment:
      - mamba install -y -n clisops -c conda-forge "python>=3.12,<3.13" "psy-maps>=1.5.0"
    pre_build:
      - env SPHINX_APIDOC_OPTIONS="members,undoc-members,show-inheritance,no-index" sphinx-apidoc -o docs/apidoc/ --private --module-first clisops

conda:
  environment: environment.yml

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
