[tox]
envlist =
    py3.{11,12,13,14}
    lint
    docs
opts = -v

[gh]
python =
    3.11 = py3.11
    3.12 = py3.12-netcdf4
    3.13 = py3.13
    3.14 = py3.14

[testenv:lint]
skip_install = True
basepython = python
deps =
    deptry >=0.25.1
    flake8 >=7.3.0
    flake8-rst-docstrings >=0.4.0
    ruff >=0.15.9
commands_pre =
    pip list
commands =
    make lint
commands_post =
allowlist_externals =
    make

[testenv:docs]
setenv =
    READTHEDOCS = 1
extras = docs
deps =
commands =
    make docs
commands_post =
allowlist_externals =
    make

[testenv]
setenv =
    PYTEST_ADDOPTS = -m "not slow" --numprocesses=logical --durations=10 --cov=clisops --cov-report=lcov
    PYTHONPATH = {toxinidir}
passenv =
    CI
    COVERALLS_*
    GITHUB_*
    LD_LIBRARY_PATH
extras = dev
install_command = python -m pip install --no-user {opts} {packages}
download = True
deps =
    netcdf4: netcdf4 >=1.6.3
    upstream: -r CI/requirements_upstream.txt
commands_pre =
    python -m pip list
    python -m pip check
commands =
    pytest {posargs}
commands_post =
    coverage report
