name: clisops
channels:
 - conda-forge
dependencies:
 - python >=3.8,<3.12
 - flit
 - bottleneck >=1.3.1
 - cf_xarray >=0.8.5
 - cftime >=1.4.1
 - dask >=2.6.0
 - gdal >=3.0
 - geopandas >=0.11
 - loguru >=0.5.3
 - netCDF4 >=1.4
 - numpy >=1.16
 - packaging
 - pandas >=1.0.3
 - pooch
 - poppler >=0.67
 - pyproj >=3.3.0
 - requests >=2.0
 - roocs-grids>=0.1.2
 - roocs-utils >=0.6.4,<0.7
 - shapely >=1.9
 - xarray >=0.21,<2023.3.0 # https://github.com/pydata/xarray/issues/7794
 - xesmf >=0.8.2
 - cartopy>=0.20.2
 - jupyterlab
 - GitPython
 - matplotlib>=3.5.2
 # Upstream
 - pip
 - pip:
   - psy-maps
   - clisops
#   - cf-xarray @ git+https://github.com/xarray-contrib/cf-xarray/@main#egg=cf-xarray
#   - roocs-utils @ git+https://github.com/roocs/roocs-utils.git@master#egg=roocs-utils
