name: clisops
channels:
 - conda-forge
dependencies:
 - python >=3.8
 - bottleneck >=1.3.1
 - cf_xarray >=0.7.5
 - cftime >=1.4.1
 - dask >=2.6.0
 - gdal >=3.0
 - geopandas >=0.11
 - loguru >=0.5.3
 - netCDF4 >=1.4
 - numba  # needed for xesmf v0.6.3, see: https://github.com/conda-forge/xesmf-feedstock/pull/24
 - numpy >=1.16
 - packaging
 - pandas >=1.0.3,<2.0
 - poppler >=0.67
 - pyproj >=3.3.0
 - pooch
 - requests >=2.0
 - roocs-utils >=0.6.4,<0.7
 - shapely >=1.9
 - sparse >=0.8.0  # needed for xesmf v0.6.3, see: https://github.com/conda-forge/xesmf-feedstock/pull/24
 - xarray >=0.21,<2023.3.0
 - xesmf >=0.7.1
 - jupyterlab
 - matplotlib>=3.5.2
 - cartopy>=0.20.2
 - GitPython
 - pip:
   - psy-maps
   - clisops @ git+https://github.com/roocs/clisops/@regrid-main#egg=clisops
   - roocs-grids @ git+https://github.com/roocs/roocs-grids.git@main#egg=roocs-grids
#   - cf-xarray @ git+https://github.com/xarray-contrib/cf-xarray/@main#egg=cf-xarray
#   - roocs-utils @ git+https://github.com/roocs/roocs-utils.git@master#egg=roocs-utils
