name: clisops
channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- bottleneck>=1.3.1,<1.4
- cf_xarray>=0.7.5
- cftime>=1.4.1
- dask>=2.6.0
- gdal==3.4.1
- geopandas>=0.7
- loguru>=0.5.3
- netCDF4>=1.4
- numpy>=1.16,<1.22
- pandas>=1.0.3,<1.4
- poppler>=0.67
- pygeos>=0.9
- pyproj>=2.5
- pooch
- requests>=2.0
- roocs-utils>=0.6.2,<0.7
- shapely>=1.6
- xarray>=0.15,<2022.6.0
- xesmf>=0.6.3
- jupyterlab
- matplotlib>=3.5.2
- cartopy>=0.20.2
- GitPython
- pip:
    - psy-maps
    - clisops @ git+https://github.com/roocs/clisops/@regrid-main#egg=clisops
#    - cf-xarray @ git+https://github.com/xarray-contrib/cf-xarray/@main#egg=cf-xarray
#    - roocs-utils @ git+https://github.com/roocs/roocs-utils.git@master#egg=roocs-utils
