name: Publish Python 🐍 distributions 📦 to TestPyPI

on:
  push:
    tags:
      - 'v*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy-testpypi:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install packaging libraries
        run: |
          python -m pip install flit
      - name: Build a binary wheel and a source tarball
        run: |
          python -m flit build
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
